<?php

namespace Database\Seeders;

use App\Models\Origin;
use Illuminate\Database\Seeder;

class OriginSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // 'id' is hardcoded on every row in this and every other seeder so
        // other seeders/files can reference it directly instead of looking
        // it up.
        $origins = [
            // Tormenta20
            ['id' => 1, 'name' => 'Acólito', 'grants' => [
                ['type' => 'choice', 'label' => 'Itens', 'picks' => 2, 'options' => [
                    ['tag' => 'accessory', 'op' => 'grant', 'accessory_id' => 1],
                    ['tag' => 'armor', 'op' => 'grant', 'armor_id' => 1],
                ]],
                ['type' => 'choice', 'label' => 'Perícias e Poderes', 'picks' => 2, 'options' => [
                    ['tag' => 'skill', 'op' => 'trains', 'skill_id' => 7],
                    ['tag' => 'skill', 'op' => 'trains', 'skill_id' => 27],
                    ['tag' => 'skill', 'op' => 'trains', 'skill_id' => 29],
                    ['tag' => 'power', 'op' => 'grant', 'power_id' => 6],
                    ['tag' => 'power', 'op' => 'grant', 'power_id' => 8],
                    ['tag' => 'power', 'op' => 'grant', 'power_id' => 7],
                ]],
            ]],
            ['id' => 2, 'name' => 'Amigo dos Animais'],
            ['id' => 3, 'name' => 'Amnésico'],
            ['id' => 4, 'name' => 'Aristocrata'],
            ['id' => 5, 'name' => 'Artesão'],
            ['id' => 6, 'name' => 'Artista'],
            ['id' => 7, 'name' => 'Assistente de Laboratório'],
            ['id' => 8, 'name' => 'Batedor'],
            ['id' => 9, 'name' => 'Capanga'],
            ['id' => 10, 'name' => 'Charlatão'],
            ['id' => 11, 'name' => 'Circense'],
            ['id' => 12, 'name' => 'Criminoso'],
            ['id' => 13, 'name' => 'Curandeiro'],
            ['id' => 14, 'name' => 'Eremita'],
            ['id' => 15, 'name' => 'Escravo'],
            ['id' => 16, 'name' => 'Estudioso'],
            ['id' => 17, 'name' => 'Fazendeiro'],
            ['id' => 18, 'name' => 'Forasteiro'],
            ['id' => 19, 'name' => 'Gladiador'],
            ['id' => 20, 'name' => 'Guarda'],
            ['id' => 21, 'name' => 'Herdeiro'],
            ['id' => 22, 'name' => 'Herói Camponês'],
            ['id' => 23, 'name' => 'Marujo'],
            ['id' => 24, 'name' => 'Mateiro'],
            ['id' => 25, 'name' => 'Membro de Guilda'],
            ['id' => 26, 'name' => 'Mercador'],
            ['id' => 27, 'name' => 'Minerador'],
            ['id' => 28, 'name' => 'Nômade'],
            ['id' => 29, 'name' => 'Pivete'],
            ['id' => 30, 'name' => 'Refugiado'],
            ['id' => 31, 'name' => 'Seguidor'],
            ['id' => 32, 'name' => 'Selvagem'],
            ['id' => 33, 'name' => 'Soldado'],
            ['id' => 34, 'name' => 'Taverneiro'],
            ['id' => 35, 'name' => 'Trabalhador'],

            // Atlas de Arton
            ['id' => 36, 'name' => 'Agricultor Sambur'],
            ['id' => 37, 'name' => 'Amazona de Hippion'],
            ['id' => 38, 'name' => 'Amoque Púrpura'],
            ['id' => 39, 'name' => 'Anão de Armas'],
            ['id' => 40, 'name' => 'Andarilho Ubaneri'],
            ['id' => 41, 'name' => 'Aprendiz de Dragoeiro'],
            ['id' => 42, 'name' => 'Aprendiz de Drogadora'],
            ['id' => 43, 'name' => 'Aristocrata Dai\'zenshi'],
            ['id' => 44, 'name' => 'Armeiro Armado'],
            ['id' => 45, 'name' => 'Aspirante a Herói'],
            ['id' => 46, 'name' => 'Assistente Forense'],
            ['id' => 47, 'name' => 'Bandoleiro da Fortaleza'],
            ['id' => 48, 'name' => 'Barão Arruinado'],
            ['id' => 49, 'name' => 'Catador da Cidade Velha'],
            ['id' => 50, 'name' => 'Cativo das Fadas'],
            ['id' => 51, 'name' => 'Competidor do Circuito'],
            ['id' => 52, 'name' => 'Cosmopolita'],
            ['id' => 53, 'name' => 'Cria da Favela'],
            ['id' => 54, 'name' => 'Cria das Estradas'],
            ['id' => 55, 'name' => 'Criado pelas Voracis'],
            ['id' => 56, 'name' => 'De Outro Mundo'],
            ['id' => 57, 'name' => 'Descendente Colleniano'],
            ['id' => 58, 'name' => 'Desertor da Supremacia'],
            ['id' => 59, 'name' => 'Duplo Feérico'],
            ['id' => 60, 'name' => 'Duyshidakk Infiltrado'],
            ['id' => 61, 'name' => 'Emissário Ubaneri'],
            ['id' => 62, 'name' => 'Escudeiro da Luz'],
            ['id' => 63, 'name' => 'Escudeiro Solitário'],
            ['id' => 64, 'name' => 'Estandarte Vivo'],
            ['id' => 65, 'name' => 'Estudante da Academia'],
            ['id' => 66, 'name' => 'Estudante do Colégio Real'],
            ['id' => 67, 'name' => 'Explorador de Ruínas'],
            ['id' => 68, 'name' => 'Filhote da Revoada'],
            ['id' => 69, 'name' => 'Futura Lenda'],
            ['id' => 70, 'name' => 'Ginete de Tumarkhân'],
            ['id' => 71, 'name' => 'Grumete Pirata'],
            ['id' => 72, 'name' => 'Guardião Glacial'],
            ['id' => 73, 'name' => 'Iniciado dos Caça-Monstros'],
            ['id' => 74, 'name' => 'Insurgente Tapistano'],
            ['id' => 75, 'name' => 'Irmão sem Esporas'],
            ['id' => 76, 'name' => 'Legionário'],
            ['id' => 77, 'name' => 'Lenhador de Tollon'],
            ['id' => 78, 'name' => 'Liricista de Lenórienn'],
            ['id' => 79, 'name' => 'Membro do Principado'],
            ['id' => 80, 'name' => 'Nitamuriano'],
            ['id' => 81, 'name' => 'Nobre Zakharoviano'],
            ['id' => 82, 'name' => 'Nômade Sar-Allan'],
            ['id' => 83, 'name' => 'Pescador Parrudo'],
            ['id' => 84, 'name' => 'Plebeu Arcano'],
            ['id' => 85, 'name' => 'Prisioneiro das Catacumbas'],
            ['id' => 86, 'name' => 'Procurado: Vivo ou Morto'],
            ['id' => 87, 'name' => 'Profeta do Akzath'],
            ['id' => 88, 'name' => 'Querido Filho'],
            ['id' => 89, 'name' => 'Rebelde Agitador'],
            ['id' => 90, 'name' => 'Receptador das Nuvens'],
            ['id' => 91, 'name' => 'Recruta Arcano'],
            ['id' => 92, 'name' => 'Recruta da Fênix'],
            ['id' => 93, 'name' => 'Sábio Matemático'],
            ['id' => 94, 'name' => 'Selvagem Sanguinário'],
            ['id' => 95, 'name' => 'Sucateiro de Batalhas'],
            ['id' => 96, 'name' => 'Tamalu'],
            ['id' => 97, 'name' => 'Tocado pela Dama Altiva'],
            ['id' => 98, 'name' => 'Tocado pelo Indomável'],
            ['id' => 99, 'name' => 'Tradicionalista Svalano'],
            ['id' => 100, 'name' => 'Trapaceiro Ahleniense'],
            ['id' => 101, 'name' => 'Turista da Academia'],
            ['id' => 102, 'name' => 'Um com os Kami'],

            // Heróis de Arton
            ['id' => 103, 'name' => 'Bacharel'],
            ['id' => 104, 'name' => 'Boticário'],
            ['id' => 105, 'name' => 'Caçador de Ratos'],
            ['id' => 106, 'name' => 'Cão de Briga'],
            ['id' => 107, 'name' => 'Carcereiro'],
            ['id' => 108, 'name' => 'Carpinteiro de Guilda'],
            ['id' => 109, 'name' => 'Catador da Catástrofe'],
            ['id' => 110, 'name' => 'Chef Hynne'],
            ['id' => 111, 'name' => 'Cirurgião-Barbeiro'],
            ['id' => 112, 'name' => 'Citadino Abastado'],
            ['id' => 113, 'name' => 'Cocheiro'],
            ['id' => 114, 'name' => 'Construtor'],
            ['id' => 115, 'name' => 'Contrabandista'],
            ['id' => 116, 'name' => 'Coureiro'],
            ['id' => 117, 'name' => 'Escriba'],
            ['id' => 118, 'name' => 'Espião'],
            ['id' => 119, 'name' => 'Ferreiro Guerreiro'],
            ['id' => 120, 'name' => 'Freira'],
            ['id' => 121, 'name' => 'Goradista'],
            ['id' => 122, 'name' => 'Insciente'],
            ['id' => 123, 'name' => 'Interrogador'],
            ['id' => 124, 'name' => 'Ladrão de Túmulos'],
            ['id' => 125, 'name' => 'Menestrel'],
            ['id' => 126, 'name' => 'Mensageiro'],
            ['id' => 127, 'name' => 'Náufrago'],
            ['id' => 128, 'name' => 'Padeiro'],
            ['id' => 129, 'name' => 'Pedinte'],
            ['id' => 130, 'name' => 'Pescador'],
            ['id' => 131, 'name' => 'Servo'],
            ['id' => 132, 'name' => 'Suporte de Tropas'],
        ];

        foreach ($origins as $origin) {
            Origin::create($origin);
        }
    }
}
