<?php

namespace Database\Seeders;

use App\Models\Origin;
use Illuminate\Database\Seeder;

class OriginSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $origins = [
            // Tormenta20
            'Acólito',
            'Amigo dos Animais',
            'Amnésico',
            'Aristocrata',
            'Artesão',
            'Artista',
            'Assistente de Laboratório',
            'Batedor',
            'Capanga',
            'Charlatão',
            'Circense',
            'Criminoso',
            'Curandeiro',
            'Eremita',
            'Escravo',
            'Estudioso',
            'Fazendeiro',
            'Forasteiro',
            'Gladiador',
            'Guarda',
            'Herdeiro',
            'Herói Camponês',
            'Marujo',
            'Mateiro',
            'Membro de Guilda',
            'Mercador',
            'Minerador',
            'Nômade',
            'Pivete',
            'Refugiado',
            'Seguidor',
            'Selvagem',
            'Soldado',
            'Taverneiro',
            'Trabalhador',

            // Atlas de Arton
            'Agricultor Sambur',
            'Amazona de Hippion',
            'Amoque Púrpura',
            'Anão de Armas',
            'Andarilho Ubaneri',
            'Aprendiz de Dragoeiro',
            'Aprendiz de Drogadora',
            'Aristocrata Dai\'zenshi',
            'Armeiro Armado',
            'Aspirante a Herói',
            'Assistente Forense',
            'Bandoleiro da Fortaleza',
            'Barão Arruinado',
            'Catador da Cidade Velha',
            'Cativo das Fadas',
            'Competidor do Circuito',
            'Cosmopolita',
            'Cria da Favela',
            'Cria das Estradas',
            'Criado pelas Voracis',
            'De Outro Mundo',
            'Descendente Colleniano',
            'Desertor da Supremacia',
            'Duplo Feérico',
            'Duyshidakk Infiltrado',
            'Emissário Ubaneri',
            'Escudeiro da Luz',
            'Escudeiro Solitário',
            'Estandarte Vivo',
            'Estudante da Academia',
            'Estudante do Colégio Real',
            'Explorador de Ruínas',
            'Filhote da Revoada',
            'Futura Lenda',
            'Ginete de Tumarkhân',
            'Grumete Pirata',
            'Guardião Glacial',
            'Iniciado dos Caça-Monstros',
            'Insurgente Tapistano',
            'Irmão sem Esporas',
            'Legionário',
            'Lenhador de Tollon',
            'Liricista de Lenórienn',
            'Membro do Principado',
            'Nitamuriano',
            'Nobre Zakharoviano',
            'Nômade Sar-Allan',
            'Pescador Parrudo',
            'Plebeu Arcano',
            'Prisioneiro das Catacumbas',
            'Procurado: Vivo ou Morto',
            'Profeta do Akzath',
            'Querido Filho',
            'Rebelde Agitador',
            'Receptador das Nuvens',
            'Recruta Arcano',
            'Recruta da Fênix',
            'Sábio Matemático',
            'Selvagem Sanguinário',
            'Sucateiro de Batalhas',
            'Tamalu',
            'Tocado pela Dama Altiva',
            'Tocado pelo Indomável',
            'Tradicionalista Svalano',
            'Trapaceiro Ahleniense',
            'Turista da Academia',
            'Um com os Kami',

            // Heróis de Arton
            'Bacharel',
            'Boticário',
            'Caçador de Ratos',
            'Cão de Briga',
            'Carcereiro',
            'Carpinteiro de Guilda',
            'Catador da Catástrofe',
            'Chef Hynne',
            'Cirurgião-Barbeiro',
            'Citadino Abastado',
            'Cocheiro',
            'Construtor',
            'Contrabandista',
            'Coureiro',
            'Escriba',
            'Espião',
            'Ferreiro Guerreiro',
            'Freira',
            'Goradista',
            'Insciente',
            'Interrogador',
            'Ladrão de Túmulos',
            'Menestrel',
            'Mensageiro',
            'Náufrago',
            'Padeiro',
            'Pedinte',
            'Pescador',
            'Servo',
            'Suporte de Tropas',
        ];

        foreach ($origins as $name) {
            Origin::create(['name' => $name]);
        }
    }
}
